<?php

return [

    [ "name" => "M-PESA"],
    [ "name" => "AIRTELMONEY"],
    [ "name" => "YUCASH"],
    [ "name" => "ORANGE MONEY"],
    [ "name" => "ABC Bank"],
    [ "name" => "ABSA Bank"],
    [ "name" => "Access Bank"],
    [ "name" => "Bank of Africa"],
    [ "name" => "Bank of Baroda"],
    [ "name" => "Bank of India"],
    [ "name" => "Citibank"],
    [ "name" => "Consolidated Bank of Kenya"],
    [ "name" => "Cooperative Bank of Kenya"],
    [ "name" => "Credit Bank"],
    [ "name" => "Development Bank of Kenya"],
    [ "name" => "Diamond Trust Bank"],
    [ "name" => "Dubai Islamic Bank"],
    [ "name" => "Ecobank Kenya"],
    [ "name" => "Equity Bank Kenya"],
    [ "name" => "Family Bank"],
    [ "name" => "First Community Bank"],
    [ "name" => "Guaranty Trust Bank"],
    [ "name" => "Guardian Bank"],
    [ "name" => "Gulf African Bank"],
    [ "name" => "Habib Bank"],
    [ "name" => "Housing Finance"],
    [ "name" => "I&M Bank"],
    [ "name" => "Imperial Bank"],
    [ "name" => "Kingdom Bank"],
    [ "name" => "KCB Bank"],
    [ "name" => "Mayfair Bank"],
    [ "name" => "Middle East Bank"],
    [ "name" => "M Oriental Bank"],
    [ "name" => "National Bank of Kenya"],
    [ "name" => "NCBA Bank Kenya"],
    [ "name" => "Paramount Universal Bank"],
    [ "name" => "Prime Bank"],
    [ "name" => "SBM Bank Kenya"],
    [ "name" => "Sidian Bank"],
    [ "name" => "Spire Bank"],
    [ "name" => "Stanbic Bank"],
    [ "name" => "Standard Chartered"],
    [ "name" => "UBA Bank"],
    [ "name" => "Victoria Commercial Bank"],
    [ "name" => "HDFC Bank"],
    [ "name" => "Nedbank"],
    [ "name" => "FirstRand Bank"],
    [ "name" => "Bank of China"],
    [ "name" => "JP Morgan Chase"],
    [ "name" => "Bank of Kigali"],
    [ "name" => "Bank AL Habib"],
    [ "name" => "Banque Misr"],

];
