<?php

return [

    ['name' => 'M-PESA'],
    ['name' => 'TIGOPESA'],
    ['name' => 'AIRTELMONEY'],
    ['name' => 'T-PESA'],
    ['name' => 'HALOPESA'],
    ['name' => 'UBA BANK'],
    ['name' => 'ECOBANK'],
    ['name' => 'MKOMBOZI COMMERCIAL BANK'],
    ['name' => 'CANARA BANK'],
    ['name' => 'BANK OF BARODA'],
    ['name' => 'STANBIC BANK'],
    ['name' => 'BANK OF AFRICA'],
    ['name' => 'HABIB AFRICAN BANK'],
    ['name' => 'KCB BANK'],
    ['name' => 'AKIBA COMMERCIAL BANK'],
    ['name' => 'NCBA BANK'],
    ['name' => 'NMB BANK'],
    ['name' => 'NBC BANK'],
    ['name' => 'INTERNATIONAL COMMERCIAL BANK'],
    ['name' => 'AZANIA BANK'],
    ['name' => 'ABSA BANK'],
    ['name' => 'I & M BANK'],
    ['name' => 'ABC Bank'],
    ['name' => 'PEOPLES BANK OF ZANZIBAR'],
    ['name' => 'CITIBANK'],
    ['name' => 'CRDB BANK'],
    ['name' => 'TCB BANK'],
    ['name' => 'DIAMOND TRUST BANK'],
    ['name' => 'STANDARD CHARTERED BANK'],
    ['name' => 'EXIM BANK'],
    ['name' => 'LETSHEGO FAIDIKA BANK'],
    ['name' => 'AMANA BANK'],
    ['name' => 'EQUITY BANK'],
    ['name' => 'MWALIMU COMMERCIAL BANK'],
    ['name' => 'GUARANTY TRUST BANK '],
    ['name' => 'CHINA DASHENG BANK'],
    ['name' => 'DCB COMMERCIAL BANK'],
    ['name' => 'BANK OF INDIA'],
    ['name' => 'MWANGA HAKIKA BANK'],
    ['name' => 'UCHUMI COMMERCIAL BANK'],
    ['name' => 'KILIMANJARO COOPERATIVE BANK'],
    ['name' => 'MUCOBA BANK'],
    ['name' => 'ACCESS MICROFINANCE BANK'],
    ['name' => 'FINCA MICROFINANCE BANK'],
    ['name' => 'VISIONFUND MICROFINANCE BANK'],
    ['name' => 'MAENDELEO BANK'],
    ['name' => 'TANDAHIMBA COMMUNITY BANK'],
    ['name' => 'Safe Account'],

];
