<?php

return [
    ['region' => 'Arusha', 'district' => 'Meru District'],
    ['region' => 'Arusha', 'district' => 'Arusha City'],
    ['region' => 'Arusha', 'district' => 'Arusha District'],
    ['region' => 'Arusha', 'district' => 'Karatu District'],
    ['region' => 'Arusha', 'district' => 'Longido District'],
    ['region' => 'Arusha', 'district' => 'Monduli District'],
    ['region' => 'Arusha', 'district' => 'Ngorongoro District'],
    ['region' => 'Dar es Salaam', 'district' => 'Ilala Municipal'],
    ['region' => 'Dar es Salaam', 'district' => 'Kinondoni Municipal'],
    ['region' => 'Dar es Salaam', 'district' => 'Temeke Municipal'],
    ['region' => 'Dar es Salaam', 'district' => 'Kigamboni Municipal'],
    ['region' => 'Dar es Salaam', 'district' => 'Ubungo Municipal'],
    ['region' => 'Dodoma', 'district' => 'Bahi District'],
    ['region' => 'Dodoma', 'district' => 'Chamwino District'],
    ['region' => 'Dodoma', 'district' => 'Chemba District'],
    ['region' => 'Dodoma', 'district' => 'Dodoma Municipal'],
    ['region' => 'Dodoma', 'district' => 'Kondoa District'],
    ['region' => 'Dodoma', 'district' => 'Kongwa District'],
    ['region' => 'Dodoma', 'district' => 'Mpwapwa District'],
    ['region' => 'Geita', 'district' => 'Bukombe District'],
    ['region' => 'Geita', 'district' => 'Chato District'],
    ['region' => 'Geita', 'district' => 'Geita Town'],
    ['region' => 'Geita', 'district' => 'Mbogwe District'],
    ['region' => 'Geita', 'district' => 'Nyang\'hwale District'],
    ['region' => 'Iringa', 'district' => 'Iringa District'],
    ['region' => 'Iringa', 'district' => 'Iringa Municipal'],
    ['region' => 'Iringa', 'district' => 'Kilolo District'],
    ['region' => 'Iringa', 'district' => 'Mafinga Town'],
    ['region' => 'Iringa', 'district' => 'Mufindi District'],
    ['region' => 'Kagera', 'district' => 'Biharamulo District'],
    ['region' => 'Kagera', 'district' => 'Bukoba District'],
    ['region' => 'Kagera', 'district' => 'Bukoba Municipal'],
    ['region' => 'Kagera', 'district' => 'Karagwe District'],
    ['region' => 'Kagera', 'district' => 'Kyerwa District'],
    ['region' => 'Kagera', 'district' => 'Missenyi District'],
    ['region' => 'Kagera', 'district' => 'Muleba District'],
    ['region' => 'Kagera', 'district' => 'Ngara District'],
    ['region' => 'Katavi', 'district' => 'Mlele District'],
    ['region' => 'Katavi', 'district' => 'Mpanda District'],
    ['region' => 'Katavi', 'district' => 'Mpanda Town'],
    ['region' => 'Kigoma', 'district' => 'Buhigwe District'],
    ['region' => 'Kigoma', 'district' => 'Kakonko District'],
    ['region' => 'Kigoma', 'district' => 'Kasulu District'],
    ['region' => 'Kigoma', 'district' => 'Kasulu Town'],
    ['region' => 'Kigoma', 'district' => 'Kibondo District'],
    ['region' => 'Kigoma', 'district' => 'Kigoma District'],
    ['region' => 'Kigoma', 'district' => 'Kigoma-Ujiji Municipal'],
    ['region' => 'Kigoma', 'district' => 'Uvinza District'],
    ['region' => 'Kilimanjaro', 'district' => 'Hai District'],
    ['region' => 'Kilimanjaro', 'district' => 'Moshi District'],
    ['region' => 'Kilimanjaro', 'district' => 'Moshi Municipal'],
    ['region' => 'Kilimanjaro', 'district' => 'Mwanga District'],
    ['region' => 'Kilimanjaro', 'district' => 'Rombo District'],
    ['region' => 'Kilimanjaro', 'district' => 'Same District'],
    ['region' => 'Kilimanjaro', 'district' => 'Siha District'],
    ['region' => 'Pemba Kusini', 'district' => 'Chake Chake District'],
    ['region' => 'Pemba Kusini', 'district' => 'Mkoani District'],
    ['region' => 'Unguja Kusini', 'district' => 'Kati District'],
    ['region' => 'Unguja Kusini', 'district' => 'Kusini District'],
    ['region' => 'Lindi', 'district' => 'Kilwa District'],
    ['region' => 'Lindi', 'district' => 'Lindi District'],
    ['region' => 'Lindi', 'district' => 'Lindi Municipal'],
    ['region' => 'Lindi', 'district' => 'Liwale District'],
    ['region' => 'Lindi', 'district' => 'Nachingwea District'],
    ['region' => 'Lindi', 'district' => 'Ruangwa District'],
    ['region' => 'Manyara', 'district' => 'Babati Town'],
    ['region' => 'Manyara', 'district' => 'Babati District'],
    ['region' => 'Manyara', 'district' => 'Hanang District'],
    ['region' => 'Manyara', 'district' => 'Kiteto District'],
    ['region' => 'Manyara', 'district' => 'Mbulu District'],
    ['region' => 'Manyara', 'district' => 'Simanjiro District'],
    ['region' => 'Mara', 'district' => 'Bunda District'],
    ['region' => 'Mara', 'district' => 'Butiama District'],
    ['region' => 'Mara', 'district' => 'Musoma District'],
    ['region' => 'Mara', 'district' => 'Musoma Municipal'],
    ['region' => 'Mara', 'district' => 'Rorya District'],
    ['region' => 'Mara', 'district' => 'Serengeti District'],
    ['region' => 'Mara', 'district' => 'Tarime District'],
    ['region' => 'Mbeya', 'district' => 'Busokelo District'],
    ['region' => 'Mbeya', 'district' => 'Chunya District'],
    ['region' => 'Mbeya', 'district' => 'Kyela District'],
    ['region' => 'Mbeya', 'district' => 'Mbarali District'],
    ['region' => 'Mbeya', 'district' => 'Mbeya City'],
    ['region' => 'Mbeya', 'district' => 'Mbeya District'],
    ['region' => 'Mbeya', 'district' => 'Rungwe'],
    ['region' => 'Unguja Mjini Magharibi', 'district' => 'Magharibi District'],
    ['region' => 'Unguja Mjini Magharibi', 'district' => 'Mjini District'],
    ['region' => 'Morogoro', 'district' => 'Gairo District'],
    ['region' => 'Morogoro', 'district' => 'Kilombero District'],
    ['region' => 'Morogoro', 'district' => 'Kilosa District'],
    ['region' => 'Morogoro', 'district' => 'Morogoro District'],
    ['region' => 'Morogoro', 'district' => 'Morogoro Municipal'],
    ['region' => 'Morogoro', 'district' => 'Mvomero District'],
    ['region' => 'Morogoro', 'district' => 'Ulanga District'],
    ['region' => 'Morogoro', 'district' => 'Malinyi District'],
    ['region' => 'Morogoro', 'district' => 'Ifakara Township'],
    ['region' => 'Mtwara', 'district' => 'Masasi District'],
    ['region' => 'Mtwara', 'district' => 'Masasi Town'],
    ['region' => 'Mtwara', 'district' => 'Mtwara District'],
    ['region' => 'Mtwara', 'district' => 'Mtwara Municipal'],
    ['region' => 'Mtwara', 'district' => 'Nanyumbu District'],
    ['region' => 'Mtwara', 'district' => 'Newala District'],
    ['region' => 'Mtwara', 'district' => 'Tandahimba District'],
    ['region' => 'Mwanza', 'district' => 'Ilemela Municipal'],
    ['region' => 'Mwanza', 'district' => 'Kwimba District'],
    ['region' => 'Mwanza', 'district' => 'Magu District'],
    ['region' => 'Mwanza', 'district' => 'Misungwi District'],
    ['region' => 'Mwanza', 'district' => 'Nyamagana Municipal'],
    ['region' => 'Mwanza', 'district' => 'Sengerema District'],
    ['region' => 'Mwanza', 'district' => 'Ukerewe District'],
    ['region' => 'Njombe', 'district' => 'Ludewa District'],
    ['region' => 'Njombe', 'district' => 'Makambako Town'],
    ['region' => 'Njombe', 'district' => 'Makete District'],
    ['region' => 'Njombe', 'district' => 'Njombe District'],
    ['region' => 'Njombe', 'district' => 'Njombe Town'],
    ['region' => 'Njombe', 'district' => 'Wanging\'ombe District'],
    ['region' => 'Pwani', 'district' => 'Bagamoyo District'],
    ['region' => 'Pwani', 'district' => 'Kibaha District'],
    ['region' => 'Pwani', 'district' => 'Kibaha Town'],
    ['region' => 'Pwani', 'district' => 'Kisarawe District'],
    ['region' => 'Pwani', 'district' => 'Mafia District'],
    ['region' => 'Pwani', 'district' => 'Mkuranga District'],
    ['region' => 'Pwani', 'district' => 'Rufiji District'],
    ['region' => 'Rukwa', 'district' => 'Kalambo District'],
    ['region' => 'Rukwa', 'district' => 'Nkasi District'],
    ['region' => 'Rukwa', 'district' => 'Sumbawanga District'],
    ['region' => 'Rukwa', 'district' => 'Sumbawanga Municipal'],
    ['region' => 'Ruvuma', 'district' => 'Mbinga District'],
    ['region' => 'Ruvuma', 'district' => 'Songea District'],
    ['region' => 'Ruvuma', 'district' => 'Songea Municipal'],
    ['region' => 'Ruvuma', 'district' => 'Tunduru District'],
    ['region' => 'Ruvuma', 'district' => 'Namtumbo District'],
    ['region' => 'Ruvuma', 'district' => 'Nyasa District'],
    ['region' => 'Shinyanga', 'district' => 'Kahama Town'],
    ['region' => 'Shinyanga', 'district' => 'Kahama District'],
    ['region' => 'Shinyanga', 'district' => 'Kishapu District'],
    ['region' => 'Shinyanga', 'district' => 'Shinyanga District'],
    ['region' => 'Shinyanga', 'district' => 'Shinyanga Municipal'],
    ['region' => 'Simiyu', 'district' => 'Bariadi District'],
    ['region' => 'Simiyu', 'district' => 'Busega District'],
    ['region' => 'Simiyu', 'district' => 'Itilima District'],
    ['region' => 'Simiyu', 'district' => 'Maswa District'],
    ['region' => 'Simiyu', 'district' => 'Meatu District'],
    ['region' => 'Singida', 'district' => 'Ikungi District'],
    ['region' => 'Singida', 'district' => 'Iramba District'],
    ['region' => 'Singida', 'district' => 'Manyoni District'],
    ['region' => 'Singida', 'district' => 'Mkalama District'],
    ['region' => 'Singida', 'district' => 'Singida District'],
    ['region' => 'Singida', 'district' => 'Singida Municipal'],
    ['region' => 'Songwe', 'district' => 'Ileje District'],
    ['region' => 'Songwe', 'district' => 'Mbozi District'],
    ['region' => 'Songwe', 'district' => 'Momba District'],
    ['region' => 'Songwe', 'district' => 'Songwe District'],
    ['region' => 'Tabora', 'district' => 'Igunga District'],
    ['region' => 'Tabora', 'district' => 'Kaliua District'],
    ['region' => 'Tabora', 'district' => 'Nzega District'],
    ['region' => 'Tabora', 'district' => 'Sikonge District'],
    ['region' => 'Tabora', 'district' => 'Tabora Municipal'],
    ['region' => 'Tabora', 'district' => 'Urambo District'],
    ['region' => 'Tabora', 'district' => 'Uyui District'],
    ['region' => 'Tanga', 'district' => 'Handeni District'],
    ['region' => 'Tanga', 'district' => 'Handeni Town'],
    ['region' => 'Tanga', 'district' => 'Kilindi District'],
    ['region' => 'Tanga', 'district' => 'Korogwe Town'],
    ['region' => 'Tanga', 'district' => 'Korogwe District'],
    ['region' => 'Tanga', 'district' => 'Lushoto District'],
    ['region' => 'Tanga', 'district' => 'Muheza District'],
    ['region' => 'Tanga', 'district' => 'Mkinga District'],
    ['region' => 'Tanga', 'district' => 'Pangani District'],
    ['region' => 'Tanga', 'district' => 'Tanga City'],
    ['region' => 'Unguja Kaskazini', 'district' => 'Kaskazini A District'],
    ['region' => 'Unguja Kaskazini', 'district' => 'Kaskazini B District'],
    ['region' => 'Pemba Kusini', 'district' => 'Micheweni District'],
    ['region' => 'Pemba Kusini', 'district' => 'Wete District'],
    ['region' => 'Unguja Mjini Magharibi', 'district' => 'Unguja Magharibi District'],
    ['region' => 'Unguja Mjini Magharibi', 'district' => 'Unguja Mjini District'],
];
